/*
 * generated by Xtext 2.25.0
 */
package ucal3ia.bilang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import ucal3ia.bilang.concretesyntax.ui.internal.ConcretesyntaxActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BiLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ConcretesyntaxActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ConcretesyntaxActivator activator = ConcretesyntaxActivator.getInstance();
		return activator != null ? activator.getInjector(ConcretesyntaxActivator.UCAL3IA_BILANG_BILANG) : null;
	}

}
