/*
 * generated by Xtext 2.25.0
 */
package ucal3ia.bilang.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BiLangGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class TaskElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.Task");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTaskKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLoadKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFileextractorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFileextractorFileExtractorParserRuleCall_4_0 = (RuleCall)cFileextractorAssignment_4.eContents().get(0);
		private final Assignment cDatafilteringAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDatafilteringDataFilteringParserRuleCall_5_0 = (RuleCall)cDatafilteringAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cFileextractorAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cFileextractorFileExtractorParserRuleCall_6_0_0 = (RuleCall)cFileextractorAssignment_6_0.eContents().get(0);
		private final Assignment cDatafilteringAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDatafilteringDataFilteringParserRuleCall_6_1_0 = (RuleCall)cDatafilteringAssignment_6_1.eContents().get(0);
		private final Keyword cDashboardKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDashboardAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDashboardDashBoardParserRuleCall_8_0 = (RuleCall)cDashboardAssignment_8.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Task returns Task:
		//    'Task'name=ID":"
		//        "load" fileextractor+=FileExtractor (datafiltering+=DataFiltering)?
		//        (fileextractor+= FileExtractor (datafiltering+= DataFiltering)?)*
		//        '[dashboard:' dashboard=DashBoard']';
		@Override public ParserRule getRule() { return rule; }
		
		//'Task'name=ID":"
		//    "load" fileextractor+=FileExtractor (datafiltering+=DataFiltering)?
		//    (fileextractor+= FileExtractor (datafiltering+= DataFiltering)?)*
		//    '[dashboard:' dashboard=DashBoard']'
		public Group getGroup() { return cGroup; }
		
		//'Task'
		public Keyword getTaskKeyword_0() { return cTaskKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//"load"
		public Keyword getLoadKeyword_3() { return cLoadKeyword_3; }
		
		//fileextractor+=FileExtractor
		public Assignment getFileextractorAssignment_4() { return cFileextractorAssignment_4; }
		
		//FileExtractor
		public RuleCall getFileextractorFileExtractorParserRuleCall_4_0() { return cFileextractorFileExtractorParserRuleCall_4_0; }
		
		//(datafiltering+=DataFiltering)?
		public Assignment getDatafilteringAssignment_5() { return cDatafilteringAssignment_5; }
		
		//DataFiltering
		public RuleCall getDatafilteringDataFilteringParserRuleCall_5_0() { return cDatafilteringDataFilteringParserRuleCall_5_0; }
		
		//(fileextractor+= FileExtractor (datafiltering+= DataFiltering)?)*
		public Group getGroup_6() { return cGroup_6; }
		
		//fileextractor+= FileExtractor
		public Assignment getFileextractorAssignment_6_0() { return cFileextractorAssignment_6_0; }
		
		//FileExtractor
		public RuleCall getFileextractorFileExtractorParserRuleCall_6_0_0() { return cFileextractorFileExtractorParserRuleCall_6_0_0; }
		
		//(datafiltering+= DataFiltering)?
		public Assignment getDatafilteringAssignment_6_1() { return cDatafilteringAssignment_6_1; }
		
		//DataFiltering
		public RuleCall getDatafilteringDataFilteringParserRuleCall_6_1_0() { return cDatafilteringDataFilteringParserRuleCall_6_1_0; }
		
		//'[dashboard:'
		public Keyword getDashboardKeyword_7() { return cDashboardKeyword_7; }
		
		//dashboard=DashBoard
		public Assignment getDashboardAssignment_8() { return cDashboardAssignment_8; }
		
		//DashBoard
		public RuleCall getDashboardDashBoardParserRuleCall_8_0() { return cDashboardDashBoardParserRuleCall_8_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_9() { return cRightSquareBracketKeyword_9; }
	}
	public class FileExtractorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.FileExtractor");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCsvExtractorParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExcelExtractorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//FileExtractor returns FileExtractor:
		//    CsvExtractor | ExcelExtractor;
		@Override public ParserRule getRule() { return rule; }
		
		//CsvExtractor | ExcelExtractor
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CsvExtractor
		public RuleCall getCsvExtractorParserRuleCall_0() { return cCsvExtractorParserRuleCall_0; }
		
		//ExcelExtractor
		public RuleCall getExcelExtractorParserRuleCall_1() { return cExcelExtractorParserRuleCall_1; }
	}
	public class FilteringStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.FilteringStep");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cQuantitativeFilteringParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cQualitativeFilteringParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//FilteringStep returns FilteringStep:
		//    QuantitativeFiltering | QualitativeFiltering;
		@Override public ParserRule getRule() { return rule; }
		
		//QuantitativeFiltering | QualitativeFiltering
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//QuantitativeFiltering
		public RuleCall getQuantitativeFilteringParserRuleCall_0() { return cQuantitativeFilteringParserRuleCall_0; }
		
		//QualitativeFiltering
		public RuleCall getQualitativeFilteringParserRuleCall_1() { return cQualitativeFilteringParserRuleCall_1; }
	}
	public class PreprocessingStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.PreprocessingStep");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMathOperationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cColReferenceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStatisticalOperationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//PreprocessingStep returns PreprocessingStep:
		//    MathOperation | ColReference | StatisticalOperation;
		@Override public ParserRule getRule() { return rule; }
		
		//MathOperation | ColReference | StatisticalOperation
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MathOperation
		public RuleCall getMathOperationParserRuleCall_0() { return cMathOperationParserRuleCall_0; }
		
		//ColReference
		public RuleCall getColReferenceParserRuleCall_1() { return cColReferenceParserRuleCall_1; }
		
		//StatisticalOperation
		public RuleCall getStatisticalOperationParserRuleCall_2() { return cStatisticalOperationParserRuleCall_2; }
	}
	public class PlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.Plot");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBarPlotParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLinePlotParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDonutPlotParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cScatterPlotParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPolarPlotParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cRadarPlotParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cPiePlotParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Plot returns Plot:
		//    BarPlot | LinePlot | DonutPlot | ScatterPlot | PolarPlot | RadarPlot | PiePlot;
		@Override public ParserRule getRule() { return rule; }
		
		//BarPlot | LinePlot | DonutPlot | ScatterPlot | PolarPlot | RadarPlot | PiePlot
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BarPlot
		public RuleCall getBarPlotParserRuleCall_0() { return cBarPlotParserRuleCall_0; }
		
		//LinePlot
		public RuleCall getLinePlotParserRuleCall_1() { return cLinePlotParserRuleCall_1; }
		
		//DonutPlot
		public RuleCall getDonutPlotParserRuleCall_2() { return cDonutPlotParserRuleCall_2; }
		
		//ScatterPlot
		public RuleCall getScatterPlotParserRuleCall_3() { return cScatterPlotParserRuleCall_3; }
		
		//PolarPlot
		public RuleCall getPolarPlotParserRuleCall_4() { return cPolarPlotParserRuleCall_4; }
		
		//RadarPlot
		public RuleCall getRadarPlotParserRuleCall_5() { return cRadarPlotParserRuleCall_5; }
		
		//PiePlot
		public RuleCall getPiePlotParserRuleCall_6() { return cPiePlotParserRuleCall_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class DataFilteringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.DataFiltering");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEqualsSignGreaterThanSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFileextractorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cFileextractorFileExtractorCrossReference_1_0 = (CrossReference)cFileextractorAssignment_1.eContents().get(0);
		private final RuleCall cFileextractorFileExtractorEStringParserRuleCall_1_0_1 = (RuleCall)cFileextractorFileExtractorCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cProcessingKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cProcessingstepAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cProcessingstepPreprocessingStepParserRuleCall_2_1_0 = (RuleCall)cProcessingstepAssignment_2_1.eContents().get(0);
		private final Assignment cProcessingstepAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cProcessingstepPreprocessingStepParserRuleCall_2_2_0 = (RuleCall)cProcessingstepAssignment_2_2.eContents().get(0);
		private final Keyword cFilteringKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFilteringstepAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFilteringstepFilteringStepParserRuleCall_4_0 = (RuleCall)cFilteringstepAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cFilteringstepAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cFilteringstepFilteringStepParserRuleCall_5_1_0 = (RuleCall)cFilteringstepAssignment_5_1.eContents().get(0);
		
		//DataFiltering returns DataFiltering:
		//    "=>" fileextractor=[FileExtractor|EString]
		//        ('processing=' processingstep+=PreprocessingStep ( processingstep+=PreprocessingStep)* )?
		//        'filtering=' filteringstep+=FilteringStep ( "," filteringstep+=FilteringStep)* ;
		@Override public ParserRule getRule() { return rule; }
		
		//"=>" fileextractor=[FileExtractor|EString]
		//    ('processing=' processingstep+=PreprocessingStep ( processingstep+=PreprocessingStep)* )?
		//    'filtering=' filteringstep+=FilteringStep ( "," filteringstep+=FilteringStep)*
		public Group getGroup() { return cGroup; }
		
		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_0() { return cEqualsSignGreaterThanSignKeyword_0; }
		
		//fileextractor=[FileExtractor|EString]
		public Assignment getFileextractorAssignment_1() { return cFileextractorAssignment_1; }
		
		//[FileExtractor|EString]
		public CrossReference getFileextractorFileExtractorCrossReference_1_0() { return cFileextractorFileExtractorCrossReference_1_0; }
		
		//EString
		public RuleCall getFileextractorFileExtractorEStringParserRuleCall_1_0_1() { return cFileextractorFileExtractorEStringParserRuleCall_1_0_1; }
		
		//('processing=' processingstep+=PreprocessingStep ( processingstep+=PreprocessingStep)* )?
		public Group getGroup_2() { return cGroup_2; }
		
		//'processing='
		public Keyword getProcessingKeyword_2_0() { return cProcessingKeyword_2_0; }
		
		//processingstep+=PreprocessingStep
		public Assignment getProcessingstepAssignment_2_1() { return cProcessingstepAssignment_2_1; }
		
		//PreprocessingStep
		public RuleCall getProcessingstepPreprocessingStepParserRuleCall_2_1_0() { return cProcessingstepPreprocessingStepParserRuleCall_2_1_0; }
		
		//( processingstep+=PreprocessingStep)*
		public Assignment getProcessingstepAssignment_2_2() { return cProcessingstepAssignment_2_2; }
		
		//PreprocessingStep
		public RuleCall getProcessingstepPreprocessingStepParserRuleCall_2_2_0() { return cProcessingstepPreprocessingStepParserRuleCall_2_2_0; }
		
		//'filtering='
		public Keyword getFilteringKeyword_3() { return cFilteringKeyword_3; }
		
		//filteringstep+=FilteringStep
		public Assignment getFilteringstepAssignment_4() { return cFilteringstepAssignment_4; }
		
		//FilteringStep
		public RuleCall getFilteringstepFilteringStepParserRuleCall_4_0() { return cFilteringstepFilteringStepParserRuleCall_4_0; }
		
		//( "," filteringstep+=FilteringStep)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//filteringstep+=FilteringStep
		public Assignment getFilteringstepAssignment_5_1() { return cFilteringstepAssignment_5_1; }
		
		//FilteringStep
		public RuleCall getFilteringstepFilteringStepParserRuleCall_5_1_0() { return cFilteringstepFilteringStepParserRuleCall_5_1_0; }
	}
	public class DashBoardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.DashBoard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cEKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cFileextractorAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final CrossReference cFileextractorFileExtractorCrossReference_2_0_1_0 = (CrossReference)cFileextractorAssignment_2_0_1.eContents().get(0);
		private final RuleCall cFileextractorFileExtractorEStringParserRuleCall_2_0_1_0_1 = (RuleCall)cFileextractorFileExtractorCrossReference_2_0_1_0.eContents().get(1);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cDfKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cDatafilteringAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final CrossReference cDatafilteringDataFilteringCrossReference_2_1_1_0 = (CrossReference)cDatafilteringAssignment_2_1_1.eContents().get(0);
		private final RuleCall cDatafilteringDataFilteringEStringParserRuleCall_2_1_1_0_1 = (RuleCall)cDatafilteringDataFilteringCrossReference_2_1_1_0.eContents().get(1);
		private final Keyword cPlotsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPlotAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPlotPlotParserRuleCall_5_0 = (RuleCall)cPlotAssignment_5.eContents().get(0);
		private final Assignment cPlotAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPlotPlotParserRuleCall_6_0 = (RuleCall)cPlotAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//DashBoard returns DashBoard:
		//    name=EString "=>" ("e" fileextractor=[FileExtractor|EString] | 'df' datafiltering=[DataFiltering|EString])
		//        'plots' '{'
		//            plot+=Plot
		//            (plot+=Plot)*
		//            '}' ;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString "=>" ("e" fileextractor=[FileExtractor|EString] | 'df' datafiltering=[DataFiltering|EString])
		//    'plots' '{'
		//        plot+=Plot
		//        (plot+=Plot)*
		//        '}'
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_1() { return cEqualsSignGreaterThanSignKeyword_1; }
		
		//("e" fileextractor=[FileExtractor|EString] | 'df' datafiltering=[DataFiltering|EString])
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//"e" fileextractor=[FileExtractor|EString]
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//"e"
		public Keyword getEKeyword_2_0_0() { return cEKeyword_2_0_0; }
		
		//fileextractor=[FileExtractor|EString]
		public Assignment getFileextractorAssignment_2_0_1() { return cFileextractorAssignment_2_0_1; }
		
		//[FileExtractor|EString]
		public CrossReference getFileextractorFileExtractorCrossReference_2_0_1_0() { return cFileextractorFileExtractorCrossReference_2_0_1_0; }
		
		//EString
		public RuleCall getFileextractorFileExtractorEStringParserRuleCall_2_0_1_0_1() { return cFileextractorFileExtractorEStringParserRuleCall_2_0_1_0_1; }
		
		//'df' datafiltering=[DataFiltering|EString]
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'df'
		public Keyword getDfKeyword_2_1_0() { return cDfKeyword_2_1_0; }
		
		//datafiltering=[DataFiltering|EString]
		public Assignment getDatafilteringAssignment_2_1_1() { return cDatafilteringAssignment_2_1_1; }
		
		//[DataFiltering|EString]
		public CrossReference getDatafilteringDataFilteringCrossReference_2_1_1_0() { return cDatafilteringDataFilteringCrossReference_2_1_1_0; }
		
		//EString
		public RuleCall getDatafilteringDataFilteringEStringParserRuleCall_2_1_1_0_1() { return cDatafilteringDataFilteringEStringParserRuleCall_2_1_1_0_1; }
		
		//'plots'
		public Keyword getPlotsKeyword_3() { return cPlotsKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//plot+=Plot
		public Assignment getPlotAssignment_5() { return cPlotAssignment_5; }
		
		//Plot
		public RuleCall getPlotPlotParserRuleCall_5_0() { return cPlotPlotParserRuleCall_5_0; }
		
		//(plot+=Plot)*
		public Assignment getPlotAssignment_6() { return cPlotAssignment_6; }
		
		//Plot
		public RuleCall getPlotPlotParserRuleCall_6_0() { return cPlotPlotParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class CsvExtractorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.CsvExtractor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCsvExtractorAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cCsvKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPathAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPathEStringParserRuleCall_4_0 = (RuleCall)cPathAssignment_4.eContents().get(0);
		
		//CsvExtractor returns CsvExtractor:
		//    {CsvExtractor}
		//    name=EString".csv" "=>" path=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{CsvExtractor}
		//name=EString".csv" "=>" path=EString
		public Group getGroup() { return cGroup; }
		
		//{CsvExtractor}
		public Action getCsvExtractorAction_0() { return cCsvExtractorAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//".csv"
		public Keyword getCsvKeyword_2() { return cCsvKeyword_2; }
		
		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_3() { return cEqualsSignGreaterThanSignKeyword_3; }
		
		//path=EString
		public Assignment getPathAssignment_4() { return cPathAssignment_4; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_4_0() { return cPathEStringParserRuleCall_4_0; }
	}
	public class ExcelExtractorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.ExcelExtractor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExcelExtractorAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cXlsxKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPathAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPathEStringParserRuleCall_4_0 = (RuleCall)cPathAssignment_4.eContents().get(0);
		
		//ExcelExtractor returns ExcelExtractor:
		//    {ExcelExtractor}
		//    name=EString".xlsx" "=>" path=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{ExcelExtractor}
		//name=EString".xlsx" "=>" path=EString
		public Group getGroup() { return cGroup; }
		
		//{ExcelExtractor}
		public Action getExcelExtractorAction_0() { return cExcelExtractorAction_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//".xlsx"
		public Keyword getXlsxKeyword_2() { return cXlsxKeyword_2; }
		
		//"=>"
		public Keyword getEqualsSignGreaterThanSignKeyword_3() { return cEqualsSignGreaterThanSignKeyword_3; }
		
		//path=EString
		public Assignment getPathAssignment_4() { return cPathAssignment_4; }
		
		//EString
		public RuleCall getPathEStringParserRuleCall_4_0() { return cPathEStringParserRuleCall_4_0; }
	}
	public class QuantitativeFilteringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.QuantitativeFiltering");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQuantitativeFilteringAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAxisAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAxisEStringParserRuleCall_1_0 = (RuleCall)cAxisAssignment_1.eContents().get(0);
		private final Assignment cOperatorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperatorQuantitativeOperatorEnumRuleCall_2_0 = (RuleCall)cOperatorAssignment_2.eContents().get(0);
		private final Assignment cValuesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValuesEFloatParserRuleCall_3_0 = (RuleCall)cValuesAssignment_3.eContents().get(0);
		
		//QuantitativeFiltering returns QuantitativeFiltering:
		//    {QuantitativeFiltering}
		//    axis= EString operator= QuantitativeOperator values= EFloat
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{QuantitativeFiltering}
		//axis= EString operator= QuantitativeOperator values= EFloat
		public Group getGroup() { return cGroup; }
		
		//{QuantitativeFiltering}
		public Action getQuantitativeFilteringAction_0() { return cQuantitativeFilteringAction_0; }
		
		//axis= EString
		public Assignment getAxisAssignment_1() { return cAxisAssignment_1; }
		
		//EString
		public RuleCall getAxisEStringParserRuleCall_1_0() { return cAxisEStringParserRuleCall_1_0; }
		
		//operator= QuantitativeOperator
		public Assignment getOperatorAssignment_2() { return cOperatorAssignment_2; }
		
		//QuantitativeOperator
		public RuleCall getOperatorQuantitativeOperatorEnumRuleCall_2_0() { return cOperatorQuantitativeOperatorEnumRuleCall_2_0; }
		
		//values= EFloat
		public Assignment getValuesAssignment_3() { return cValuesAssignment_3; }
		
		//EFloat
		public RuleCall getValuesEFloatParserRuleCall_3_0() { return cValuesEFloatParserRuleCall_3_0; }
	}
	public class QualitativeFilteringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.QualitativeFiltering");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cQualitativeFilteringAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cAxisAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAxisEStringParserRuleCall_1_0 = (RuleCall)cAxisAssignment_1.eContents().get(0);
		private final Assignment cOperatorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperatorQualitativeOperatorEnumRuleCall_2_0 = (RuleCall)cOperatorAssignment_2.eContents().get(0);
		private final Assignment cLabelsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLabelsEStringParserRuleCall_3_0 = (RuleCall)cLabelsAssignment_3.eContents().get(0);
		
		//QualitativeFiltering returns QualitativeFiltering:
		//    {QualitativeFiltering}
		//    axis= EString operator= QualitativeOperator labels= EString
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{QualitativeFiltering}
		//axis= EString operator= QualitativeOperator labels= EString
		public Group getGroup() { return cGroup; }
		
		//{QualitativeFiltering}
		public Action getQualitativeFilteringAction_0() { return cQualitativeFilteringAction_0; }
		
		//axis= EString
		public Assignment getAxisAssignment_1() { return cAxisAssignment_1; }
		
		//EString
		public RuleCall getAxisEStringParserRuleCall_1_0() { return cAxisEStringParserRuleCall_1_0; }
		
		//operator= QualitativeOperator
		public Assignment getOperatorAssignment_2() { return cOperatorAssignment_2; }
		
		//QualitativeOperator
		public RuleCall getOperatorQualitativeOperatorEnumRuleCall_2_0() { return cOperatorQualitativeOperatorEnumRuleCall_2_0; }
		
		//labels= EString
		public Assignment getLabelsAssignment_3() { return cLabelsAssignment_3; }
		
		//EString
		public RuleCall getLabelsEStringParserRuleCall_3_0() { return cLabelsEStringParserRuleCall_3_0; }
	}
	public class MathOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.MathOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLsideAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLsidePreprocessingStepParserRuleCall_1_0 = (RuleCall)cLsideAssignment_1.eContents().get(0);
		private final Assignment cOperatorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOperatorMathOperatorEnumRuleCall_2_0 = (RuleCall)cOperatorAssignment_2.eContents().get(0);
		private final Keyword cRKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRsideAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRsidePreprocessingStepParserRuleCall_4_0 = (RuleCall)cRsideAssignment_4.eContents().get(0);
		
		//MathOperation returns MathOperation:
		//    'l' lside=PreprocessingStep operator=MathOperator 'r' rside=PreprocessingStep;
		@Override public ParserRule getRule() { return rule; }
		
		//'l' lside=PreprocessingStep operator=MathOperator 'r' rside=PreprocessingStep
		public Group getGroup() { return cGroup; }
		
		//'l'
		public Keyword getLKeyword_0() { return cLKeyword_0; }
		
		//lside=PreprocessingStep
		public Assignment getLsideAssignment_1() { return cLsideAssignment_1; }
		
		//PreprocessingStep
		public RuleCall getLsidePreprocessingStepParserRuleCall_1_0() { return cLsidePreprocessingStepParserRuleCall_1_0; }
		
		//operator=MathOperator
		public Assignment getOperatorAssignment_2() { return cOperatorAssignment_2; }
		
		//MathOperator
		public RuleCall getOperatorMathOperatorEnumRuleCall_2_0() { return cOperatorMathOperatorEnumRuleCall_2_0; }
		
		//'r'
		public Keyword getRKeyword_3() { return cRKeyword_3; }
		
		//rside=PreprocessingStep
		public Assignment getRsideAssignment_4() { return cRsideAssignment_4; }
		
		//PreprocessingStep
		public RuleCall getRsidePreprocessingStepParserRuleCall_4_0() { return cRsidePreprocessingStepParserRuleCall_4_0; }
	}
	public class ColReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.ColReference");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cColReferenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTargetAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTargetEStringParserRuleCall_1_0 = (RuleCall)cTargetAssignment_1.eContents().get(0);
		
		//ColReference returns ColReference:
		//    {ColReference}
		//    target= EString
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{ColReference}
		//target= EString
		public Group getGroup() { return cGroup; }
		
		//{ColReference}
		public Action getColReferenceAction_0() { return cColReferenceAction_0; }
		
		//target= EString
		public Assignment getTargetAssignment_1() { return cTargetAssignment_1; }
		
		//EString
		public RuleCall getTargetEStringParserRuleCall_1_0() { return cTargetEStringParserRuleCall_1_0; }
	}
	public class StatisticalOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.StatisticalOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperatorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOperatorStatisticalOperatorEnumRuleCall_0_0 = (RuleCall)cOperatorAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColreferenceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColreferenceColReferenceParserRuleCall_2_0 = (RuleCall)cColreferenceAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//StatisticalOperation returns StatisticalOperation:
		//    operator=StatisticalOperator"("colreference=ColReference")";
		@Override public ParserRule getRule() { return rule; }
		
		//operator=StatisticalOperator"("colreference=ColReference")"
		public Group getGroup() { return cGroup; }
		
		//operator=StatisticalOperator
		public Assignment getOperatorAssignment_0() { return cOperatorAssignment_0; }
		
		//StatisticalOperator
		public RuleCall getOperatorStatisticalOperatorEnumRuleCall_0_0() { return cOperatorStatisticalOperatorEnumRuleCall_0_0; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//colreference=ColReference
		public Assignment getColreferenceAssignment_2() { return cColreferenceAssignment_2; }
		
		//ColReference
		public RuleCall getColreferenceColReferenceParserRuleCall_2_0() { return cColreferenceColReferenceParserRuleCall_2_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat returns ecore::EFloat:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class BarPlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.BarPlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBarPlotAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBarKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cXAxKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAxisAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXAxisEStringParserRuleCall_5_0 = (RuleCall)cXAxisAssignment_5.eContents().get(0);
		private final Keyword cYAKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cYAxisAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cYAxisEStringParserRuleCall_7_0 = (RuleCall)cYAxisAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLocKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cLocationAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cLocationEStringParserRuleCall_8_1_0 = (RuleCall)cLocationAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cColorsKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cColorsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cColorsEStringParserRuleCall_9_1_0 = (RuleCall)cColorsAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cThicknessKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cThicknessAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cThicknessEFloatParserRuleCall_10_1_0 = (RuleCall)cThicknessAssignment_10_1.eContents().get(0);
		
		//BarPlot returns BarPlot:
		//    {BarPlot}
		//    'bar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{BarPlot}
		//'bar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		public Group getGroup() { return cGroup; }
		
		//{BarPlot}
		public Action getBarPlotAction_0() { return cBarPlotAction_0; }
		
		//'bar'
		public Keyword getBarKeyword_1() { return cBarKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_3() { return cHyphenMinusGreaterThanSignKeyword_3; }
		
		//'xAx'
		public Keyword getXAxKeyword_4() { return cXAxKeyword_4; }
		
		//xAxis=EString
		public Assignment getXAxisAssignment_5() { return cXAxisAssignment_5; }
		
		//EString
		public RuleCall getXAxisEStringParserRuleCall_5_0() { return cXAxisEStringParserRuleCall_5_0; }
		
		//'yA'
		public Keyword getYAKeyword_6() { return cYAKeyword_6; }
		
		//yAxis=EString
		public Assignment getYAxisAssignment_7() { return cYAxisAssignment_7; }
		
		//EString
		public RuleCall getYAxisEStringParserRuleCall_7_0() { return cYAxisEStringParserRuleCall_7_0; }
		
		//('loc' location=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'loc'
		public Keyword getLocKeyword_8_0() { return cLocKeyword_8_0; }
		
		//location=EString
		public Assignment getLocationAssignment_8_1() { return cLocationAssignment_8_1; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_8_1_0() { return cLocationEStringParserRuleCall_8_1_0; }
		
		//('colors' colors=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'colors'
		public Keyword getColorsKeyword_9_0() { return cColorsKeyword_9_0; }
		
		//colors=EString
		public Assignment getColorsAssignment_9_1() { return cColorsAssignment_9_1; }
		
		//EString
		public RuleCall getColorsEStringParserRuleCall_9_1_0() { return cColorsEStringParserRuleCall_9_1_0; }
		
		//('thickness' thickness=EFloat)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'thickness'
		public Keyword getThicknessKeyword_10_0() { return cThicknessKeyword_10_0; }
		
		//thickness=EFloat
		public Assignment getThicknessAssignment_10_1() { return cThicknessAssignment_10_1; }
		
		//EFloat
		public RuleCall getThicknessEFloatParserRuleCall_10_1_0() { return cThicknessEFloatParserRuleCall_10_1_0; }
	}
	public class LinePlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.LinePlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLinePlotAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cXAxKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAxisAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXAxisEStringParserRuleCall_5_0 = (RuleCall)cXAxisAssignment_5.eContents().get(0);
		private final Keyword cYAKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cYAxisAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cYAxisEStringParserRuleCall_7_0 = (RuleCall)cYAxisAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cLocKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cLocationAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cLocationEStringParserRuleCall_8_1_0 = (RuleCall)cLocationAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cColorsKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cColorsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cColorsEStringParserRuleCall_9_1_0 = (RuleCall)cColorsAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cThicknessKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cThicknessAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cThicknessEFloatParserRuleCall_10_1_0 = (RuleCall)cThicknessAssignment_10_1.eContents().get(0);
		
		//LinePlot returns LinePlot:
		//    {LinePlot}
		//    'line' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{LinePlot}
		//'line' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		public Group getGroup() { return cGroup; }
		
		//{LinePlot}
		public Action getLinePlotAction_0() { return cLinePlotAction_0; }
		
		//'line'
		public Keyword getLineKeyword_1() { return cLineKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_3() { return cHyphenMinusGreaterThanSignKeyword_3; }
		
		//'xAx'
		public Keyword getXAxKeyword_4() { return cXAxKeyword_4; }
		
		//xAxis=EString
		public Assignment getXAxisAssignment_5() { return cXAxisAssignment_5; }
		
		//EString
		public RuleCall getXAxisEStringParserRuleCall_5_0() { return cXAxisEStringParserRuleCall_5_0; }
		
		//'yA'
		public Keyword getYAKeyword_6() { return cYAKeyword_6; }
		
		//yAxis=EString
		public Assignment getYAxisAssignment_7() { return cYAxisAssignment_7; }
		
		//EString
		public RuleCall getYAxisEStringParserRuleCall_7_0() { return cYAxisEStringParserRuleCall_7_0; }
		
		//('loc' location=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'loc'
		public Keyword getLocKeyword_8_0() { return cLocKeyword_8_0; }
		
		//location=EString
		public Assignment getLocationAssignment_8_1() { return cLocationAssignment_8_1; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_8_1_0() { return cLocationEStringParserRuleCall_8_1_0; }
		
		//('colors' colors=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'colors'
		public Keyword getColorsKeyword_9_0() { return cColorsKeyword_9_0; }
		
		//colors=EString
		public Assignment getColorsAssignment_9_1() { return cColorsAssignment_9_1; }
		
		//EString
		public RuleCall getColorsEStringParserRuleCall_9_1_0() { return cColorsEStringParserRuleCall_9_1_0; }
		
		//('thickness' thickness=EFloat)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'thickness'
		public Keyword getThicknessKeyword_10_0() { return cThicknessKeyword_10_0; }
		
		//thickness=EFloat
		public Assignment getThicknessAssignment_10_1() { return cThicknessAssignment_10_1; }
		
		//EFloat
		public RuleCall getThicknessEFloatParserRuleCall_10_1_0() { return cThicknessEFloatParserRuleCall_10_1_0; }
	}
	public class DonutPlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.DonutPlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDonutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cXAxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXAxisAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXAxisEStringParserRuleCall_4_0 = (RuleCall)cXAxisAssignment_4.eContents().get(0);
		private final Keyword cYAKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cYAxisAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cYAxisEStringParserRuleCall_6_0 = (RuleCall)cYAxisAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLocKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLocationAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cLocationEStringParserRuleCall_7_1_0 = (RuleCall)cLocationAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cColorsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cColorsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cColorsEStringParserRuleCall_8_1_0 = (RuleCall)cColorsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cThicknessKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cThicknessAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cThicknessEFloatParserRuleCall_9_1_0 = (RuleCall)cThicknessAssignment_9_1.eContents().get(0);
		
		//DonutPlot returns DonutPlot:
		//     'donut' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'donut' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		public Group getGroup() { return cGroup; }
		
		//'donut'
		public Keyword getDonutKeyword_0() { return cDonutKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'xAx'
		public Keyword getXAxKeyword_3() { return cXAxKeyword_3; }
		
		//xAxis=EString
		public Assignment getXAxisAssignment_4() { return cXAxisAssignment_4; }
		
		//EString
		public RuleCall getXAxisEStringParserRuleCall_4_0() { return cXAxisEStringParserRuleCall_4_0; }
		
		//'yA'
		public Keyword getYAKeyword_5() { return cYAKeyword_5; }
		
		//yAxis=EString
		public Assignment getYAxisAssignment_6() { return cYAxisAssignment_6; }
		
		//EString
		public RuleCall getYAxisEStringParserRuleCall_6_0() { return cYAxisEStringParserRuleCall_6_0; }
		
		//('loc' location=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'loc'
		public Keyword getLocKeyword_7_0() { return cLocKeyword_7_0; }
		
		//location=EString
		public Assignment getLocationAssignment_7_1() { return cLocationAssignment_7_1; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_7_1_0() { return cLocationEStringParserRuleCall_7_1_0; }
		
		//('colors' colors=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'colors'
		public Keyword getColorsKeyword_8_0() { return cColorsKeyword_8_0; }
		
		//colors=EString
		public Assignment getColorsAssignment_8_1() { return cColorsAssignment_8_1; }
		
		//EString
		public RuleCall getColorsEStringParserRuleCall_8_1_0() { return cColorsEStringParserRuleCall_8_1_0; }
		
		//('thickness' thickness=EFloat)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'thickness'
		public Keyword getThicknessKeyword_9_0() { return cThicknessKeyword_9_0; }
		
		//thickness=EFloat
		public Assignment getThicknessAssignment_9_1() { return cThicknessAssignment_9_1; }
		
		//EFloat
		public RuleCall getThicknessEFloatParserRuleCall_9_1_0() { return cThicknessEFloatParserRuleCall_9_1_0; }
	}
	public class PiePlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.PiePlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPieKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cXAxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXAxisAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXAxisEStringParserRuleCall_4_0 = (RuleCall)cXAxisAssignment_4.eContents().get(0);
		private final Keyword cYAKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cYAxisAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cYAxisEStringParserRuleCall_6_0 = (RuleCall)cYAxisAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLocKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLocationAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cLocationEStringParserRuleCall_7_1_0 = (RuleCall)cLocationAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cColorsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cColorsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cColorsEStringParserRuleCall_8_1_0 = (RuleCall)cColorsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cThicknessKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cThicknessAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cThicknessEFloatParserRuleCall_9_1_0 = (RuleCall)cThicknessAssignment_9_1.eContents().get(0);
		
		//PiePlot returns PiePlot:
		//    'pie' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'pie' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		public Group getGroup() { return cGroup; }
		
		//'pie'
		public Keyword getPieKeyword_0() { return cPieKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'xAx'
		public Keyword getXAxKeyword_3() { return cXAxKeyword_3; }
		
		//xAxis=EString
		public Assignment getXAxisAssignment_4() { return cXAxisAssignment_4; }
		
		//EString
		public RuleCall getXAxisEStringParserRuleCall_4_0() { return cXAxisEStringParserRuleCall_4_0; }
		
		//'yA'
		public Keyword getYAKeyword_5() { return cYAKeyword_5; }
		
		//yAxis=EString
		public Assignment getYAxisAssignment_6() { return cYAxisAssignment_6; }
		
		//EString
		public RuleCall getYAxisEStringParserRuleCall_6_0() { return cYAxisEStringParserRuleCall_6_0; }
		
		//('loc' location=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'loc'
		public Keyword getLocKeyword_7_0() { return cLocKeyword_7_0; }
		
		//location=EString
		public Assignment getLocationAssignment_7_1() { return cLocationAssignment_7_1; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_7_1_0() { return cLocationEStringParserRuleCall_7_1_0; }
		
		//('colors' colors=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'colors'
		public Keyword getColorsKeyword_8_0() { return cColorsKeyword_8_0; }
		
		//colors=EString
		public Assignment getColorsAssignment_8_1() { return cColorsAssignment_8_1; }
		
		//EString
		public RuleCall getColorsEStringParserRuleCall_8_1_0() { return cColorsEStringParserRuleCall_8_1_0; }
		
		//('thickness' thickness=EFloat)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'thickness'
		public Keyword getThicknessKeyword_9_0() { return cThicknessKeyword_9_0; }
		
		//thickness=EFloat
		public Assignment getThicknessAssignment_9_1() { return cThicknessAssignment_9_1; }
		
		//EFloat
		public RuleCall getThicknessEFloatParserRuleCall_9_1_0() { return cThicknessEFloatParserRuleCall_9_1_0; }
	}
	public class PolarPlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.PolarPlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPolarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cXAxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXAxisAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXAxisEStringParserRuleCall_4_0 = (RuleCall)cXAxisAssignment_4.eContents().get(0);
		private final Keyword cYAKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cYAxisAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cYAxisEStringParserRuleCall_6_0 = (RuleCall)cYAxisAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLocKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLocationAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cLocationEStringParserRuleCall_7_1_0 = (RuleCall)cLocationAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cColorsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cColorsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cColorsEStringParserRuleCall_8_1_0 = (RuleCall)cColorsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cThicknessKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cThicknessAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cThicknessEFloatParserRuleCall_9_1_0 = (RuleCall)cThicknessAssignment_9_1.eContents().get(0);
		
		//PolarPlot returns PolarPlot:
		//    'polar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'polar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		public Group getGroup() { return cGroup; }
		
		//'polar'
		public Keyword getPolarKeyword_0() { return cPolarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'xAx'
		public Keyword getXAxKeyword_3() { return cXAxKeyword_3; }
		
		//xAxis=EString
		public Assignment getXAxisAssignment_4() { return cXAxisAssignment_4; }
		
		//EString
		public RuleCall getXAxisEStringParserRuleCall_4_0() { return cXAxisEStringParserRuleCall_4_0; }
		
		//'yA'
		public Keyword getYAKeyword_5() { return cYAKeyword_5; }
		
		//yAxis=EString
		public Assignment getYAxisAssignment_6() { return cYAxisAssignment_6; }
		
		//EString
		public RuleCall getYAxisEStringParserRuleCall_6_0() { return cYAxisEStringParserRuleCall_6_0; }
		
		//('loc' location=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'loc'
		public Keyword getLocKeyword_7_0() { return cLocKeyword_7_0; }
		
		//location=EString
		public Assignment getLocationAssignment_7_1() { return cLocationAssignment_7_1; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_7_1_0() { return cLocationEStringParserRuleCall_7_1_0; }
		
		//('colors' colors=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'colors'
		public Keyword getColorsKeyword_8_0() { return cColorsKeyword_8_0; }
		
		//colors=EString
		public Assignment getColorsAssignment_8_1() { return cColorsAssignment_8_1; }
		
		//EString
		public RuleCall getColorsEStringParserRuleCall_8_1_0() { return cColorsEStringParserRuleCall_8_1_0; }
		
		//('thickness' thickness=EFloat)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'thickness'
		public Keyword getThicknessKeyword_9_0() { return cThicknessKeyword_9_0; }
		
		//thickness=EFloat
		public Assignment getThicknessAssignment_9_1() { return cThicknessAssignment_9_1; }
		
		//EFloat
		public RuleCall getThicknessEFloatParserRuleCall_9_1_0() { return cThicknessEFloatParserRuleCall_9_1_0; }
	}
	public class ScatterPlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.ScatterPlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScatterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cXAxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXAxisAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXAxisEStringParserRuleCall_4_0 = (RuleCall)cXAxisAssignment_4.eContents().get(0);
		private final Keyword cYAKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cYAxisAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cYAxisEStringParserRuleCall_6_0 = (RuleCall)cYAxisAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLocKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLocationAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cLocationEStringParserRuleCall_7_1_0 = (RuleCall)cLocationAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cColorsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cColorsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cColorsEStringParserRuleCall_8_1_0 = (RuleCall)cColorsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cThicknessKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cThicknessAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cThicknessEFloatParserRuleCall_9_1_0 = (RuleCall)cThicknessAssignment_9_1.eContents().get(0);
		
		//ScatterPlot returns ScatterPlot:
		//    'scatter' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'scatter' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		public Group getGroup() { return cGroup; }
		
		//'scatter'
		public Keyword getScatterKeyword_0() { return cScatterKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'xAx'
		public Keyword getXAxKeyword_3() { return cXAxKeyword_3; }
		
		//xAxis=EString
		public Assignment getXAxisAssignment_4() { return cXAxisAssignment_4; }
		
		//EString
		public RuleCall getXAxisEStringParserRuleCall_4_0() { return cXAxisEStringParserRuleCall_4_0; }
		
		//'yA'
		public Keyword getYAKeyword_5() { return cYAKeyword_5; }
		
		//yAxis=EString
		public Assignment getYAxisAssignment_6() { return cYAxisAssignment_6; }
		
		//EString
		public RuleCall getYAxisEStringParserRuleCall_6_0() { return cYAxisEStringParserRuleCall_6_0; }
		
		//('loc' location=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'loc'
		public Keyword getLocKeyword_7_0() { return cLocKeyword_7_0; }
		
		//location=EString
		public Assignment getLocationAssignment_7_1() { return cLocationAssignment_7_1; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_7_1_0() { return cLocationEStringParserRuleCall_7_1_0; }
		
		//('colors' colors=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'colors'
		public Keyword getColorsKeyword_8_0() { return cColorsKeyword_8_0; }
		
		//colors=EString
		public Assignment getColorsAssignment_8_1() { return cColorsAssignment_8_1; }
		
		//EString
		public RuleCall getColorsEStringParserRuleCall_8_1_0() { return cColorsEStringParserRuleCall_8_1_0; }
		
		//('thickness' thickness=EFloat)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'thickness'
		public Keyword getThicknessKeyword_9_0() { return cThicknessKeyword_9_0; }
		
		//thickness=EFloat
		public Assignment getThicknessAssignment_9_1() { return cThicknessAssignment_9_1; }
		
		//EFloat
		public RuleCall getThicknessEFloatParserRuleCall_9_1_0() { return cThicknessEFloatParserRuleCall_9_1_0; }
	}
	public class RadarPlotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.RadarPlot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRadarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cXAxKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXAxisAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXAxisEStringParserRuleCall_4_0 = (RuleCall)cXAxisAssignment_4.eContents().get(0);
		private final Keyword cYAKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cYAxisAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cYAxisEStringParserRuleCall_6_0 = (RuleCall)cYAxisAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLocKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLocationAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cLocationEStringParserRuleCall_7_1_0 = (RuleCall)cLocationAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cColorsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cColorsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cColorsEStringParserRuleCall_8_1_0 = (RuleCall)cColorsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cThicknessKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cThicknessAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cThicknessEFloatParserRuleCall_9_1_0 = (RuleCall)cThicknessAssignment_9_1.eContents().get(0);
		
		//RadarPlot returns RadarPlot:
		//    'radar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'radar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
		public Group getGroup() { return cGroup; }
		
		//'radar'
		public Keyword getRadarKeyword_0() { return cRadarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_2() { return cHyphenMinusGreaterThanSignKeyword_2; }
		
		//'xAx'
		public Keyword getXAxKeyword_3() { return cXAxKeyword_3; }
		
		//xAxis=EString
		public Assignment getXAxisAssignment_4() { return cXAxisAssignment_4; }
		
		//EString
		public RuleCall getXAxisEStringParserRuleCall_4_0() { return cXAxisEStringParserRuleCall_4_0; }
		
		//'yA'
		public Keyword getYAKeyword_5() { return cYAKeyword_5; }
		
		//yAxis=EString
		public Assignment getYAxisAssignment_6() { return cYAxisAssignment_6; }
		
		//EString
		public RuleCall getYAxisEStringParserRuleCall_6_0() { return cYAxisEStringParserRuleCall_6_0; }
		
		//('loc' location=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'loc'
		public Keyword getLocKeyword_7_0() { return cLocKeyword_7_0; }
		
		//location=EString
		public Assignment getLocationAssignment_7_1() { return cLocationAssignment_7_1; }
		
		//EString
		public RuleCall getLocationEStringParserRuleCall_7_1_0() { return cLocationEStringParserRuleCall_7_1_0; }
		
		//('colors' colors=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'colors'
		public Keyword getColorsKeyword_8_0() { return cColorsKeyword_8_0; }
		
		//colors=EString
		public Assignment getColorsAssignment_8_1() { return cColorsAssignment_8_1; }
		
		//EString
		public RuleCall getColorsEStringParserRuleCall_8_1_0() { return cColorsEStringParserRuleCall_8_1_0; }
		
		//('thickness' thickness=EFloat)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'thickness'
		public Keyword getThicknessKeyword_9_0() { return cThicknessKeyword_9_0; }
		
		//thickness=EFloat
		public Assignment getThicknessAssignment_9_1() { return cThicknessAssignment_9_1; }
		
		//EFloat
		public RuleCall getThicknessEFloatParserRuleCall_9_1_0() { return cThicknessEFloatParserRuleCall_9_1_0; }
	}
	
	public class MathOperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.MathOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPLUSEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPLUSPlusSignKeyword_0_0 = (Keyword)cPLUSEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMINUSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMINUSHyphenMinusKeyword_1_0 = (Keyword)cMINUSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMULTIPLYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMULTIPLYAsteriskKeyword_2_0 = (Keyword)cMULTIPLYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDIVIDINGEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDIVIDINGSolidusKeyword_3_0 = (Keyword)cDIVIDINGEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum MathOperator returns MathOperator:
		//                PLUS = '+' | MINUS = '-' | MULTIPLY = '*' | DIVIDING = '/';
		public EnumRule getRule() { return rule; }
		
		//PLUS = '+' | MINUS = '-' | MULTIPLY = '*' | DIVIDING = '/'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PLUS = '+'
		public EnumLiteralDeclaration getPLUSEnumLiteralDeclaration_0() { return cPLUSEnumLiteralDeclaration_0; }
		
		//'+'
		public Keyword getPLUSPlusSignKeyword_0_0() { return cPLUSPlusSignKeyword_0_0; }
		
		//MINUS = '-'
		public EnumLiteralDeclaration getMINUSEnumLiteralDeclaration_1() { return cMINUSEnumLiteralDeclaration_1; }
		
		//'-'
		public Keyword getMINUSHyphenMinusKeyword_1_0() { return cMINUSHyphenMinusKeyword_1_0; }
		
		//MULTIPLY = '*'
		public EnumLiteralDeclaration getMULTIPLYEnumLiteralDeclaration_2() { return cMULTIPLYEnumLiteralDeclaration_2; }
		
		//'*'
		public Keyword getMULTIPLYAsteriskKeyword_2_0() { return cMULTIPLYAsteriskKeyword_2_0; }
		
		//DIVIDING = '/'
		public EnumLiteralDeclaration getDIVIDINGEnumLiteralDeclaration_3() { return cDIVIDINGEnumLiteralDeclaration_3; }
		
		//'/'
		public Keyword getDIVIDINGSolidusKeyword_3_0() { return cDIVIDINGSolidusKeyword_3_0; }
	}
	public class StatisticalOperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.StatisticalOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMEANEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMEANMeanKeyword_0_0 = (Keyword)cMEANEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMEDIANEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMEDIANMedianKeyword_1_0 = (Keyword)cMEDIANEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSTDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSTDStdKeyword_2_0 = (Keyword)cSTDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum StatisticalOperator returns StatisticalOperator:
		//                MEAN = 'mean' | MEDIAN = 'median' | STD = 'std';
		public EnumRule getRule() { return rule; }
		
		//MEAN = 'mean' | MEDIAN = 'median' | STD = 'std'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MEAN = 'mean'
		public EnumLiteralDeclaration getMEANEnumLiteralDeclaration_0() { return cMEANEnumLiteralDeclaration_0; }
		
		//'mean'
		public Keyword getMEANMeanKeyword_0_0() { return cMEANMeanKeyword_0_0; }
		
		//MEDIAN = 'median'
		public EnumLiteralDeclaration getMEDIANEnumLiteralDeclaration_1() { return cMEDIANEnumLiteralDeclaration_1; }
		
		//'median'
		public Keyword getMEDIANMedianKeyword_1_0() { return cMEDIANMedianKeyword_1_0; }
		
		//STD = 'std'
		public EnumLiteralDeclaration getSTDEnumLiteralDeclaration_2() { return cSTDEnumLiteralDeclaration_2; }
		
		//'std'
		public Keyword getSTDStdKeyword_2_0() { return cSTDStdKeyword_2_0; }
	}
	public class QualitativeOperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.QualitativeOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEQUALSEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEQUALSEqualsSignSpaceKeyword_0_0 = (Keyword)cEQUALSEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNOTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNOTExclamationMarkEqualsSignSpaceKeyword_1_0 = (Keyword)cNOTEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum QualitativeOperator returns QualitativeOperator:
		//    EQUALS= "= " | NOT= "!= "
		//;
		public EnumRule getRule() { return rule; }
		
		//EQUALS= "= " | NOT= "!= "
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EQUALS= "= "
		public EnumLiteralDeclaration getEQUALSEnumLiteralDeclaration_0() { return cEQUALSEnumLiteralDeclaration_0; }
		
		//"= "
		public Keyword getEQUALSEqualsSignSpaceKeyword_0_0() { return cEQUALSEqualsSignSpaceKeyword_0_0; }
		
		//NOT= "!= "
		public EnumLiteralDeclaration getNOTEnumLiteralDeclaration_1() { return cNOTEnumLiteralDeclaration_1; }
		
		//"!= "
		public Keyword getNOTExclamationMarkEqualsSignSpaceKeyword_1_0() { return cNOTExclamationMarkEqualsSignSpaceKeyword_1_0; }
	}
	public class QuantitativeOperatorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ucal3ia.bilang.BiLang.QuantitativeOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEQUALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEQUALEqualsSignKeyword_0_0 = (Keyword)cEQUALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cINFERIOREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cINFERIORLessThanSignKeyword_1_0 = (Keyword)cINFERIOREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSUPERIOREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSUPERIORGreaterThanSignKeyword_2_0 = (Keyword)cSUPERIOREnumLiteralDeclaration_2.eContents().get(0);
		
		//enum QuantitativeOperator returns QuantitativeOperator:
		//    EQUAL= "=" | INFERIOR= "<" | SUPERIOR= ">"
		//;
		public EnumRule getRule() { return rule; }
		
		//EQUAL= "=" | INFERIOR= "<" | SUPERIOR= ">"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EQUAL= "="
		public EnumLiteralDeclaration getEQUALEnumLiteralDeclaration_0() { return cEQUALEnumLiteralDeclaration_0; }
		
		//"="
		public Keyword getEQUALEqualsSignKeyword_0_0() { return cEQUALEqualsSignKeyword_0_0; }
		
		//INFERIOR= "<"
		public EnumLiteralDeclaration getINFERIOREnumLiteralDeclaration_1() { return cINFERIOREnumLiteralDeclaration_1; }
		
		//"<"
		public Keyword getINFERIORLessThanSignKeyword_1_0() { return cINFERIORLessThanSignKeyword_1_0; }
		
		//SUPERIOR= ">"
		public EnumLiteralDeclaration getSUPERIOREnumLiteralDeclaration_2() { return cSUPERIOREnumLiteralDeclaration_2; }
		
		//">"
		public Keyword getSUPERIORGreaterThanSignKeyword_2_0() { return cSUPERIORGreaterThanSignKeyword_2_0; }
	}
	
	private final TaskElements pTask;
	private final FileExtractorElements pFileExtractor;
	private final FilteringStepElements pFilteringStep;
	private final PreprocessingStepElements pPreprocessingStep;
	private final PlotElements pPlot;
	private final EStringElements pEString;
	private final DataFilteringElements pDataFiltering;
	private final DashBoardElements pDashBoard;
	private final CsvExtractorElements pCsvExtractor;
	private final ExcelExtractorElements pExcelExtractor;
	private final QuantitativeFilteringElements pQuantitativeFiltering;
	private final QualitativeFilteringElements pQualitativeFiltering;
	private final MathOperationElements pMathOperation;
	private final ColReferenceElements pColReference;
	private final StatisticalOperationElements pStatisticalOperation;
	private final EFloatElements pEFloat;
	private final BarPlotElements pBarPlot;
	private final LinePlotElements pLinePlot;
	private final DonutPlotElements pDonutPlot;
	private final PiePlotElements pPiePlot;
	private final PolarPlotElements pPolarPlot;
	private final ScatterPlotElements pScatterPlot;
	private final RadarPlotElements pRadarPlot;
	private final MathOperatorElements eMathOperator;
	private final StatisticalOperatorElements eStatisticalOperator;
	private final QualitativeOperatorElements eQualitativeOperator;
	private final QuantitativeOperatorElements eQuantitativeOperator;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BiLangGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTask = new TaskElements();
		this.pFileExtractor = new FileExtractorElements();
		this.pFilteringStep = new FilteringStepElements();
		this.pPreprocessingStep = new PreprocessingStepElements();
		this.pPlot = new PlotElements();
		this.pEString = new EStringElements();
		this.pDataFiltering = new DataFilteringElements();
		this.pDashBoard = new DashBoardElements();
		this.pCsvExtractor = new CsvExtractorElements();
		this.pExcelExtractor = new ExcelExtractorElements();
		this.pQuantitativeFiltering = new QuantitativeFilteringElements();
		this.pQualitativeFiltering = new QualitativeFilteringElements();
		this.pMathOperation = new MathOperationElements();
		this.pColReference = new ColReferenceElements();
		this.pStatisticalOperation = new StatisticalOperationElements();
		this.pEFloat = new EFloatElements();
		this.pBarPlot = new BarPlotElements();
		this.pLinePlot = new LinePlotElements();
		this.pDonutPlot = new DonutPlotElements();
		this.pPiePlot = new PiePlotElements();
		this.pPolarPlot = new PolarPlotElements();
		this.pScatterPlot = new ScatterPlotElements();
		this.pRadarPlot = new RadarPlotElements();
		this.eMathOperator = new MathOperatorElements();
		this.eStatisticalOperator = new StatisticalOperatorElements();
		this.eQualitativeOperator = new QualitativeOperatorElements();
		this.eQuantitativeOperator = new QuantitativeOperatorElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ucal3ia.bilang.BiLang".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Task returns Task:
	//    'Task'name=ID":"
	//        "load" fileextractor+=FileExtractor (datafiltering+=DataFiltering)?
	//        (fileextractor+= FileExtractor (datafiltering+= DataFiltering)?)*
	//        '[dashboard:' dashboard=DashBoard']';
	public TaskElements getTaskAccess() {
		return pTask;
	}
	
	public ParserRule getTaskRule() {
		return getTaskAccess().getRule();
	}
	
	//FileExtractor returns FileExtractor:
	//    CsvExtractor | ExcelExtractor;
	public FileExtractorElements getFileExtractorAccess() {
		return pFileExtractor;
	}
	
	public ParserRule getFileExtractorRule() {
		return getFileExtractorAccess().getRule();
	}
	
	//FilteringStep returns FilteringStep:
	//    QuantitativeFiltering | QualitativeFiltering;
	public FilteringStepElements getFilteringStepAccess() {
		return pFilteringStep;
	}
	
	public ParserRule getFilteringStepRule() {
		return getFilteringStepAccess().getRule();
	}
	
	//PreprocessingStep returns PreprocessingStep:
	//    MathOperation | ColReference | StatisticalOperation;
	public PreprocessingStepElements getPreprocessingStepAccess() {
		return pPreprocessingStep;
	}
	
	public ParserRule getPreprocessingStepRule() {
		return getPreprocessingStepAccess().getRule();
	}
	
	//Plot returns Plot:
	//    BarPlot | LinePlot | DonutPlot | ScatterPlot | PolarPlot | RadarPlot | PiePlot;
	public PlotElements getPlotAccess() {
		return pPlot;
	}
	
	public ParserRule getPlotRule() {
		return getPlotAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//DataFiltering returns DataFiltering:
	//    "=>" fileextractor=[FileExtractor|EString]
	//        ('processing=' processingstep+=PreprocessingStep ( processingstep+=PreprocessingStep)* )?
	//        'filtering=' filteringstep+=FilteringStep ( "," filteringstep+=FilteringStep)* ;
	public DataFilteringElements getDataFilteringAccess() {
		return pDataFiltering;
	}
	
	public ParserRule getDataFilteringRule() {
		return getDataFilteringAccess().getRule();
	}
	
	//DashBoard returns DashBoard:
	//    name=EString "=>" ("e" fileextractor=[FileExtractor|EString] | 'df' datafiltering=[DataFiltering|EString])
	//        'plots' '{'
	//            plot+=Plot
	//            (plot+=Plot)*
	//            '}' ;
	public DashBoardElements getDashBoardAccess() {
		return pDashBoard;
	}
	
	public ParserRule getDashBoardRule() {
		return getDashBoardAccess().getRule();
	}
	
	//CsvExtractor returns CsvExtractor:
	//    {CsvExtractor}
	//    name=EString".csv" "=>" path=EString;
	public CsvExtractorElements getCsvExtractorAccess() {
		return pCsvExtractor;
	}
	
	public ParserRule getCsvExtractorRule() {
		return getCsvExtractorAccess().getRule();
	}
	
	//ExcelExtractor returns ExcelExtractor:
	//    {ExcelExtractor}
	//    name=EString".xlsx" "=>" path=EString;
	public ExcelExtractorElements getExcelExtractorAccess() {
		return pExcelExtractor;
	}
	
	public ParserRule getExcelExtractorRule() {
		return getExcelExtractorAccess().getRule();
	}
	
	//QuantitativeFiltering returns QuantitativeFiltering:
	//    {QuantitativeFiltering}
	//    axis= EString operator= QuantitativeOperator values= EFloat
	//    ;
	public QuantitativeFilteringElements getQuantitativeFilteringAccess() {
		return pQuantitativeFiltering;
	}
	
	public ParserRule getQuantitativeFilteringRule() {
		return getQuantitativeFilteringAccess().getRule();
	}
	
	//QualitativeFiltering returns QualitativeFiltering:
	//    {QualitativeFiltering}
	//    axis= EString operator= QualitativeOperator labels= EString
	//    ;
	public QualitativeFilteringElements getQualitativeFilteringAccess() {
		return pQualitativeFiltering;
	}
	
	public ParserRule getQualitativeFilteringRule() {
		return getQualitativeFilteringAccess().getRule();
	}
	
	//MathOperation returns MathOperation:
	//    'l' lside=PreprocessingStep operator=MathOperator 'r' rside=PreprocessingStep;
	public MathOperationElements getMathOperationAccess() {
		return pMathOperation;
	}
	
	public ParserRule getMathOperationRule() {
		return getMathOperationAccess().getRule();
	}
	
	//ColReference returns ColReference:
	//    {ColReference}
	//    target= EString
	//    ;
	public ColReferenceElements getColReferenceAccess() {
		return pColReference;
	}
	
	public ParserRule getColReferenceRule() {
		return getColReferenceAccess().getRule();
	}
	
	//StatisticalOperation returns StatisticalOperation:
	//    operator=StatisticalOperator"("colreference=ColReference")";
	public StatisticalOperationElements getStatisticalOperationAccess() {
		return pStatisticalOperation;
	}
	
	public ParserRule getStatisticalOperationRule() {
		return getStatisticalOperationAccess().getRule();
	}
	
	//EFloat returns ecore::EFloat:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//BarPlot returns BarPlot:
	//    {BarPlot}
	//    'bar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?;
	public BarPlotElements getBarPlotAccess() {
		return pBarPlot;
	}
	
	public ParserRule getBarPlotRule() {
		return getBarPlotAccess().getRule();
	}
	
	//LinePlot returns LinePlot:
	//    {LinePlot}
	//    'line' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?;
	public LinePlotElements getLinePlotAccess() {
		return pLinePlot;
	}
	
	public ParserRule getLinePlotRule() {
		return getLinePlotAccess().getRule();
	}
	
	//DonutPlot returns DonutPlot:
	//     'donut' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?;
	public DonutPlotElements getDonutPlotAccess() {
		return pDonutPlot;
	}
	
	public ParserRule getDonutPlotRule() {
		return getDonutPlotAccess().getRule();
	}
	
	//PiePlot returns PiePlot:
	//    'pie' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
	//;
	public PiePlotElements getPiePlotAccess() {
		return pPiePlot;
	}
	
	public ParserRule getPiePlotRule() {
		return getPiePlotAccess().getRule();
	}
	
	//PolarPlot returns PolarPlot:
	//    'polar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
	//;
	public PolarPlotElements getPolarPlotAccess() {
		return pPolarPlot;
	}
	
	public ParserRule getPolarPlotRule() {
		return getPolarPlotAccess().getRule();
	}
	
	//ScatterPlot returns ScatterPlot:
	//    'scatter' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
	//;
	public ScatterPlotElements getScatterPlotAccess() {
		return pScatterPlot;
	}
	
	public ParserRule getScatterPlotRule() {
		return getScatterPlotAccess().getRule();
	}
	
	//RadarPlot returns RadarPlot:
	//    'radar' name=ID "->" 'xAx' xAxis=EString 'yA' yAxis=EString ('loc' location=EString)? ('colors' colors=EString)? ('thickness' thickness=EFloat)?
	//;
	public RadarPlotElements getRadarPlotAccess() {
		return pRadarPlot;
	}
	
	public ParserRule getRadarPlotRule() {
		return getRadarPlotAccess().getRule();
	}
	
	//enum MathOperator returns MathOperator:
	//                PLUS = '+' | MINUS = '-' | MULTIPLY = '*' | DIVIDING = '/';
	public MathOperatorElements getMathOperatorAccess() {
		return eMathOperator;
	}
	
	public EnumRule getMathOperatorRule() {
		return getMathOperatorAccess().getRule();
	}
	
	//enum StatisticalOperator returns StatisticalOperator:
	//                MEAN = 'mean' | MEDIAN = 'median' | STD = 'std';
	public StatisticalOperatorElements getStatisticalOperatorAccess() {
		return eStatisticalOperator;
	}
	
	public EnumRule getStatisticalOperatorRule() {
		return getStatisticalOperatorAccess().getRule();
	}
	
	//enum QualitativeOperator returns QualitativeOperator:
	//    EQUALS= "= " | NOT= "!= "
	//;
	public QualitativeOperatorElements getQualitativeOperatorAccess() {
		return eQualitativeOperator;
	}
	
	public EnumRule getQualitativeOperatorRule() {
		return getQualitativeOperatorAccess().getRule();
	}
	
	//enum QuantitativeOperator returns QuantitativeOperator:
	//    EQUAL= "=" | INFERIOR= "<" | SUPERIOR= ">"
	//;
	public QuantitativeOperatorElements getQuantitativeOperatorAccess() {
		return eQuantitativeOperator;
	}
	
	public EnumRule getQuantitativeOperatorRule() {
		return getQuantitativeOperatorAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
