<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BiLang" nsURI="http://www.example.org/BiLang" nsPrefix="BiLang">
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileextractor" lowerBound="1"
        upperBound="-1" eType="#//FileExtractor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datafiltering" upperBound="-1"
        eType="#//DataFiltering" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dashboard" lowerBound="1"
        upperBound="-1" eType="#//DashBoard" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileExtractor" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CsvExtractor" eSuperTypes="#//FileExtractor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelExtractor" eSuperTypes="#//FileExtractor"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataFiltering" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteringsteps" lowerBound="1"
        upperBound="-1" eType="#//FilteringSteps" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessingsteps" upperBound="-1"
        eType="#//PreprocessingSteps" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileextractor" lowerBound="1"
        eType="#//FileExtractor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DashBoard" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileextractor" eType="#//FileExtractor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datafiltering" eType="#//DataFiltering"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plot" lowerBound="1" upperBound="-1"
        eType="#//Plot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinePlot" eSuperTypes="#//Plot"/>
  <eClassifiers xsi:type="ecore:EClass" name="BarPlot" eSuperTypes="#//Plot"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringSteps" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="axis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreprocessingSteps" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QuantitativeFiltering" eSuperTypes="#//FilteringSteps">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualitativeFiltering" eSuperTypes="#//FilteringSteps">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathOperation" eSuperTypes="#//PreprocessingSteps">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lside" lowerBound="1" eType="#//PreprocessingSteps"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rside" lowerBound="1" eType="#//PreprocessingSteps"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//MathOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatisticalOperation" eSuperTypes="#//PreprocessingSteps">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preprocessingsteps" lowerBound="1"
        eType="#//PreprocessingSteps" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//StatisticalOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="colReference" eSuperTypes="#//PreprocessingSteps">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MathOperator">
    <eLiterals name="PLUS" literal="+"/>
    <eLiterals name="MINUS" value="1" literal="-"/>
    <eLiterals name="MULTIPLY" value="2" literal="*"/>
    <eLiterals name="DIVIDING" value="3" literal="/"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatisticalOperator">
    <eLiterals name="MEAN" literal="mean"/>
    <eLiterals name="MEDIAN" value="1" literal="median"/>
    <eLiterals name="STD" value="2" literal="std"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plot" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xAxis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yAxis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thickness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
