/*
 * generated by Xtext 2.25.0
 */
package ucal3ia.bilang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BiLangUiModule extends AbstractBiLangUiModule {

	public BiLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
