/*
 * generated by Xtext 2.25.0
 */
package ucal3ia.bilang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ucal3ia.bilang.BiLangRuntimeModule;
import ucal3ia.bilang.BiLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BiLangIdeSetup extends BiLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BiLangRuntimeModule(), new BiLangIdeModule()));
	}
	
}
