/*
 * generated by Xtext 2.25.0
 */
package ucal3ia.bilang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ucal3ia.bilang.parser.antlr.internal.InternalBiLangParser;
import ucal3ia.bilang.services.BiLangGrammarAccess;

public class BiLangParser extends AbstractAntlrParser {

	@Inject
	private BiLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBiLangParser createParser(XtextTokenStream stream) {
		return new InternalBiLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Task";
	}

	public BiLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BiLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
