/*
 * generated by Xtext 2.25.0
 */
package ucal3ia.bilang.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import ucal3ia.bilang.services.BiLangGrammarAccess;

@SuppressWarnings("all")
public class BiLangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected BiLangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_MathOperation_LeftParenthesisKeyword_0_q;
	protected AbstractElementAlias match_MathOperation_RightParenthesisKeyword_6_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (BiLangGrammarAccess) access;
		match_MathOperation_LeftParenthesisKeyword_0_q = new TokenAlias(false, true, grammarAccess.getMathOperationAccess().getLeftParenthesisKeyword_0());
		match_MathOperation_RightParenthesisKeyword_6_q = new TokenAlias(false, true, grammarAccess.getMathOperationAccess().getRightParenthesisKeyword_6());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_MathOperation_LeftParenthesisKeyword_0_q.equals(syntax))
				emit_MathOperation_LeftParenthesisKeyword_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_MathOperation_RightParenthesisKeyword_6_q.equals(syntax))
				emit_MathOperation_RightParenthesisKeyword_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'l' lside=PreprocessingStep
	 */
	protected void emit_MathOperation_LeftParenthesisKeyword_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ')'?
	 *
	 * This ambiguous syntax occurs at:
	 *     rside=PreprocessingStep (ambiguity) (rule end)
	 */
	protected void emit_MathOperation_RightParenthesisKeyword_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
